# Generated by Django 4.2.4 on 2023-09-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('net', models.FloatField()),
                ('garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.garde')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.month')),
            ],
        ),
    ]
